version: '3.9'

services:
  web:
    build: .
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    command: >
      sh -c "
        sleep 10 &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py import_data feedback.json &&
        python manage.py collectstatic --no-input &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    expose:
      - 8000
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=qmeteruser
      - MONGODB_PASSWORD=qmeterpassword
      - MONGODB_DB=qmeter
    networks:
      - app_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./feedback.json:/feedback.json
    networks:
      - app_network

  nginx:
    image: nginx:latest
    build: ./nginx
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - web

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
  static_volume:
